credentials:
  usernames:
    GeneticsKU@Admins:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Admins
      password: admins@geneticsku # Will be hashed automatically
    yanawat4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Yanawat_4511
      password: yanawat4511 # Will be hashed automatically
    viroj4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Viroj_4511
      password: viroj4511 # Will be hashed automatically
    kongtawan4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Kongtawan_4511
      password: kongtawan4511 # Will be hashed automatically
    pornchai4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Pornchai_4511
      password: pornchai4511 # Will be hashed automatically
    narumon4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Narumon_4511
      password: narumon4511 # Will be hashed automatically
    pornpavee4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Pornpavee_4511
      password: pornpavee4511 # Will be hashed automatically
    supanida4511 :
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Supanida_4511
      password: supanida4511 # Will be hashed automatically
    khemrutai4511:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Khemrutai_4511
      password: khemrutai4511 # Will be hashed automatically

cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  
  
